setup: |
  echo "🐊 All project dependencies have been installed!"
---

# perform checks on a file
- writing/temp.md:
    - description: Ensure that the temp.md files exist
      check: ConfirmFileExists
    - description: No TODOs remain in the temp.md files
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Write a minimum number of meaningful words (500) in the temp.md
      check: CountFileWords
      options:
        count: 500
        exact: false

# count number of commits in the GitHub repository
- description: Have at least 3 of commits in repository
  check: CountCommits
  options:
    count: 3
